---
title: '!TITLE!'
output: html_document
---

!INTRODUCTION!

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Rooms {.tabset .tabset-fade .tabset-pills}





###Room 1


|                      |2277                                                                                                                                                              |
|:---------------------|:-----------------------------------------------------------------------------------------------------------------------------------------------------------------|
|Name                  |Smugglers                                                                                                                                                         |
|CR                    |2                                                                                                                                                                 |
|XP                    |600                                                                                                                                                               |
|Race                  |Human                                                                                                                                                             |
|Class1                |rogue                                                                                                                                                             |
|Class1_Lvl            |3                                                                                                                                                                 |
|Class2                |                                                                                                                                                                  |
|Class2_Lvl            |NA                                                                                                                                                                |
|Alignment             |CN                                                                                                                                                                |
|Size                  |Medium                                                                                                                                                            |
|Type                  |humanoid                                                                                                                                                          |
|subtype1              |human                                                                                                                                                             |
|subtype2              |                                                                                                                                                                  |
|subtype3              |                                                                                                                                                                  |
|subtype4              |                                                                                                                                                                  |
|subtype5              |                                                                                                                                                                  |
|subtype6              |                                                                                                                                                                  |
|AC                    |15                                                                                                                                                                |
|AC_Touch              |12                                                                                                                                                                |
|AC_Flat.footed        |13                                                                                                                                                                |
|HP                    |20                                                                                                                                                                |
|HD                    |3d8+3                                                                                                                                                             |
|Fort                  |0                                                                                                                                                                 |
|Ref                   |5                                                                                                                                                                 |
|Will                  |2                                                                                                                                                                 |
|Melee                 |mwk scimitar +3 (1d6/18-20), sap +4 (1d6 nonlethal)                                                                                                               |
|Ranged                |shortbow +4 (1d6/x3)                                                                                                                                              |
|Space                 |5                                                                                                                                                                 |
|Reach                 |5                                                                                                                                                                 |
|Str                   |10                                                                                                                                                                |
|Dex                   |14                                                                                                                                                                |
|Con                   |8                                                                                                                                                                 |
|Int                   |12                                                                                                                                                                |
|Wis                   |13                                                                                                                                                                |
|Cha                   |17                                                                                                                                                                |
|Feats                 |Improved Initiative, Toughness, Weapon Finesse                                                                                                                    |
|Skills                |Appraise +7, Bluff +9, Diplomacy +9, Disguise +9, Intimidate +9, Knowledge (local) +7, Perception +7, Sense Motive +7, Sleight of Hand +8, Stealth +8             |
|RacialMods            |                                                                                                                                                                  |
|Languages             |                                                                                                                                                                  |
|SQ                    |bribery*, conceal item*, distraction*, rogue talents (fast stealth)                                                                                               |
|Environment           |any oceans or coastlines                                                                                                                                          |
|Organization          |solitary, pair, or team (3-5)                                                                                                                                     |
|Treasure              |NPC gear (masterwork studded leather, sap, masterwork scimitar, shortbow with 20 arrows, potion of eagle's splendor, potions of invisibility [2], other treasure) |
|Group                 |Pirate                                                                                                                                                            |
|Gear                  |                                                                                                                                                                  |
|OtherGear             |                                                                                                                                                                  |
|CharacterFlag         |0                                                                                                                                                                 |
|CompanionFlag         |0                                                                                                                                                                 |
|Speed                 |30 ft.                                                                                                                                                            |
|Base_Speed            |30                                                                                                                                                                |
|Fly_Speed             |                                                                                                                                                                  |
|Maneuverability       |                                                                                                                                                                  |
|Climb_Speed           |                                                                                                                                                                  |
|Swim_Speed            |                                                                                                                                                                  |
|Burrow_Speed          |                                                                                                                                                                  |
|Speed_Special         |                                                                                                                                                                  |
|Speed_Land            |1                                                                                                                                                                 |
|Fly                   |0                                                                                                                                                                 |
|Climb                 |0                                                                                                                                                                 |
|Burrow                |0                                                                                                                                                                 |
|Swim                  |0                                                                                                                                                                 |
|VariantParent         |                                                                                                                                                                  |
|ClassArchetypes       |smuggler                                                                                                                                                          |
|CompanionFamiliarLink |NULL                                                                                                                                                              |
|AlternateNameForm     |                                                                                                                                                                  |
|id                    |2745                                                                                                                                                              |
|UniqueMonster         |0                                                                                                                                                                 |
|MR                    |0                                                                                                                                                                 |
|Mythic                |0                                                                                                                                                                 |
|MT                    |0                                                                                                                                                                 |
|Source                |Isles Of The Shackles                                                                                                                                             |
|N                     |1                                                                                                                                                                 |
|hp                    |12                                                                                                                                                                |


###Room 2


|                      |71                                                                                |
|:---------------------|:---------------------------------------------------------------------------------|
|Name                  |Albino Cave Spider                                                                |
|CR                    |0.5                                                                               |
|XP                    |200                                                                               |
|Race                  |                                                                                  |
|Class1                |                                                                                  |
|Class1_Lvl            |NA                                                                                |
|Class2                |                                                                                  |
|Class2_Lvl            |NA                                                                                |
|Alignment             |N                                                                                 |
|Size                  |Tiny                                                                              |
|Type                  |vermin                                                                            |
|subtype1              |                                                                                  |
|subtype2              |                                                                                  |
|subtype3              |                                                                                  |
|subtype4              |                                                                                  |
|subtype5              |                                                                                  |
|subtype6              |                                                                                  |
|AC                    |17                                                                                |
|AC_Touch              |16                                                                                |
|AC_Flat.footed        |13                                                                                |
|HP                    |4                                                                                 |
|HD                    |1d8                                                                               |
|Fort                  |2                                                                                 |
|Ref                   |4                                                                                 |
|Will                  |0                                                                                 |
|Melee                 |bite +6 (1d3-3 plus poison)                                                       |
|Ranged                |                                                                                  |
|Space                 |2.50                                                                              |
|Reach                 |2.50                                                                              |
|Str                   |4                                                                                 |
|Dex                   |18                                                                                |
|Con                   |10                                                                                |
|Int                   |-                                                                                 |
|Wis                   |10                                                                                |
|Cha                   |3                                                                                 |
|Feats                 |Weapon Finesse B                                                                  |
|Skills                |Acrobatics +4 (+12 jump), Climb +12, Stealth +16                                  |
|RacialMods            |+8 to Acrobatics when jumping, +4 Perception, +4 Stealth; use Dex to modify Climb |
|Languages             |                                                                                  |
|SQ                    |                                                                                  |
|Environment           |underground                                                                       |
|Organization          |solitary or nest (2-20)                                                           |
|Treasure              |standard                                                                          |
|Group                 |Spider                                                                            |
|Gear                  |                                                                                  |
|OtherGear             |                                                                                  |
|CharacterFlag         |0                                                                                 |
|CompanionFlag         |0                                                                                 |
|Speed                 |20 ft., climb 10 ft.                                                              |
|Base_Speed            |20                                                                                |
|Fly_Speed             |                                                                                  |
|Maneuverability       |                                                                                  |
|Climb_Speed           |                                                                                  |
|Swim_Speed            |                                                                                  |
|Burrow_Speed          |                                                                                  |
|Speed_Special         |                                                                                  |
|Speed_Land            |1                                                                                 |
|Fly                   |0                                                                                 |
|Climb                 |1                                                                                 |
|Burrow                |0                                                                                 |
|Swim                  |0                                                                                 |
|VariantParent         |NULL                                                                              |
|ClassArchetypes       |                                                                                  |
|CompanionFamiliarLink |NULL                                                                              |
|AlternateNameForm     |                                                                                  |
|id                    |5067                                                                              |
|UniqueMonster         |0                                                                                 |
|MR                    |0                                                                                 |
|Mythic                |0                                                                                 |
|MT                    |0                                                                                 |
|Source                |Tome of Horrors 4                                                                 |
|N                     |2                                                                                 |
|hp                    |5  , 7                                                                            |


###Room 3


|                      |2102                                       |
|:---------------------|:------------------------------------------|
|Name                  |Scarab Beetle                              |
|CR                    |6                                          |
|XP                    |2,400                                      |
|Race                  |                                           |
|Class1                |                                           |
|Class1_Lvl            |NA                                         |
|Class2                |                                           |
|Class2_Lvl            |NA                                         |
|Alignment             |N                                          |
|Size                  |Large                                      |
|Type                  |vermin                                     |
|subtype1              |                                           |
|subtype2              |                                           |
|subtype3              |                                           |
|subtype4              |                                           |
|subtype5              |                                           |
|subtype6              |                                           |
|AC                    |20                                         |
|AC_Touch              |10                                         |
|AC_Flat.footed        |19                                         |
|HP                    |67                                         |
|HD                    |9d8+27                                     |
|Fort                  |9                                          |
|Ref                   |4                                          |
|Will                  |3                                          |
|Melee                 |bite +11 (1d8+9 plus gnaw)                 |
|Ranged                |                                           |
|Space                 |10                                         |
|Reach                 |5                                          |
|Str                   |23                                         |
|Dex                   |12                                         |
|Con                   |16                                         |
|Int                   |-                                          |
|Wis                   |10                                         |
|Cha                   |1                                          |
|Feats                 |                                           |
|Skills                |Climb +14, Fly -1                          |
|RacialMods            |                                           |
|Languages             |                                           |
|SQ                    |                                           |
|Environment           |warm deserts                               |
|Organization          |solitary or swarm (3-9)                    |
|Treasure              |none                                       |
|Group                 |Beetle                                     |
|Gear                  |                                           |
|OtherGear             |                                           |
|CharacterFlag         |0                                          |
|CompanionFlag         |0                                          |
|Speed                 |40 ft., climb 20 ft., fly 20 ft. (average) |
|Base_Speed            |40                                         |
|Fly_Speed             |20                                         |
|Maneuverability       |                                           |
|Climb_Speed           |                                           |
|Swim_Speed            |                                           |
|Burrow_Speed          |                                           |
|Speed_Special         |                                           |
|Speed_Land            |1                                          |
|Fly                   |1                                          |
|Climb                 |1                                          |
|Burrow                |0                                          |
|Swim                  |0                                          |
|VariantParent         |                                           |
|ClassArchetypes       |                                           |
|CompanionFamiliarLink |NULL                                       |
|AlternateNameForm     |                                           |
|id                    |3553                                       |
|UniqueMonster         |0                                          |
|MR                    |0                                          |
|Mythic                |0                                          |
|MT                    |0                                          |
|Source                |Inner Sea Bestiary                         |
|N                     |1                                          |
|hp                    |77                                         |


###Room 4


|                      |339                                                                                                                                                                      |
|:---------------------|:------------------------------------------------------------------------------------------------------------------------------------------------------------------------|
|Name                  |Broken Soul Lillend                                                                                                                                                      |
|CR                    |9                                                                                                                                                                        |
|XP                    |6,400                                                                                                                                                                    |
|Race                  |                                                                                                                                                                         |
|Class1                |                                                                                                                                                                         |
|Class1_Lvl            |NA                                                                                                                                                                       |
|Class2                |                                                                                                                                                                         |
|Class2_Lvl            |NA                                                                                                                                                                       |
|Alignment             |CE                                                                                                                                                                       |
|Size                  |Large                                                                                                                                                                    |
|Type                  |outsider                                                                                                                                                                 |
|subtype1              |azata                                                                                                                                                                    |
|subtype2              |chaotic                                                                                                                                                                  |
|subtype3              |extraplanar                                                                                                                                                              |
|subtype4              |evil                                                                                                                                                                     |
|subtype5              |                                                                                                                                                                         |
|subtype6              |                                                                                                                                                                         |
|AC                    |24                                                                                                                                                                       |
|AC_Touch              |12                                                                                                                                                                       |
|AC_Flat.footed        |21                                                                                                                                                                       |
|HP                    |101                                                                                                                                                                      |
|HD                    |7d10+63                                                                                                                                                                  |
|Fort                  |12                                                                                                                                                                       |
|Ref                   |10                                                                                                                                                                       |
|Will                  |6                                                                                                                                                                        |
|Melee                 |+1 longsword +12/+7 (2d6+8/19-20), tail slap +6 (2d6+2 plus grab) or torturous touch +11 touch (2d6 plus 1d6 Dex damage and convulsions), tail slap +6 (2d6+2 plus grab) |
|Ranged                |                                                                                                                                                                         |
|Space                 |10                                                                                                                                                                       |
|Reach                 |10                                                                                                                                                                       |
|Str                   |20                                                                                                                                                                       |
|Dex                   |17                                                                                                                                                                       |
|Con                   |27                                                                                                                                                                       |
|Int                   |14                                                                                                                                                                       |
|Wis                   |8                                                                                                                                                                        |
|Cha                   |21                                                                                                                                                                       |
|Feats                 |Combat Casting, DiehardB, EnduranceB, Great FortitudeB, Hover, Iron Will, Lightning Reflexes, ToughnessB                                                                 |
|Skills                |Bluff +15, Fly +11, Intimidate +13, Knowledge (nature) +9, Perception +9, Perform (string) +17, Sense Motive +9, Stealth +9, Survival +10                                |
|RacialMods            |+8 Intimidate, +4 Survival                                                                                                                                               |
|Languages             |Celestial, Draconic, Infernal; truespeech                                                                                                                                |
|SQ                    |                                                                                                                                                                         |
|Environment           |any                                                                                                                                                                      |
|Organization          |solitary                                                                                                                                                                 |
|Treasure              |standard (+1 longsword, masterwork harp, other treasure)                                                                                                                 |
|Group                 |Broken Soul                                                                                                                                                              |
|Gear                  |                                                                                                                                                                         |
|OtherGear             |                                                                                                                                                                         |
|CharacterFlag         |0                                                                                                                                                                        |
|CompanionFlag         |0                                                                                                                                                                        |
|Speed                 |20 ft., fly 60 ft. (average)                                                                                                                                             |
|Base_Speed            |20                                                                                                                                                                       |
|Fly_Speed             |                                                                                                                                                                         |
|Maneuverability       |average                                                                                                                                                                  |
|Climb_Speed           |                                                                                                                                                                         |
|Swim_Speed            |                                                                                                                                                                         |
|Burrow_Speed          |                                                                                                                                                                         |
|Speed_Special         |                                                                                                                                                                         |
|Speed_Land            |1                                                                                                                                                                        |
|Fly                   |1                                                                                                                                                                        |
|Climb                 |0                                                                                                                                                                        |
|Burrow                |0                                                                                                                                                                        |
|Swim                  |0                                                                                                                                                                        |
|VariantParent         |                                                                                                                                                                         |
|ClassArchetypes       |                                                                                                                                                                         |
|CompanionFamiliarLink |NULL                                                                                                                                                                     |
|AlternateNameForm     |                                                                                                                                                                         |
|id                    |5151                                                                                                                                                                     |
|UniqueMonster         |0                                                                                                                                                                        |
|MR                    |0                                                                                                                                                                        |
|Mythic                |0                                                                                                                                                                        |
|MT                    |0                                                                                                                                                                        |
|Source                |PFRPG Bestiary 4                                                                                                                                                         |
|N                     |2                                                                                                                                                                        |
|hp                    |90  , 99                                                                                                                                                                 |


###Room 5


|                      |808                                                                                                                                                                  |
|:---------------------|:--------------------------------------------------------------------------------------------------------------------------------------------------------------------|
|Name                  |Fext                                                                                                                                                                 |
|CR                    |10                                                                                                                                                                   |
|XP                    |9,600                                                                                                                                                                |
|Race                  |                                                                                                                                                                     |
|Class1                |                                                                                                                                                                     |
|Class1_Lvl            |NA                                                                                                                                                                   |
|Class2                |                                                                                                                                                                     |
|Class2_Lvl            |NA                                                                                                                                                                   |
|Alignment             |LE                                                                                                                                                                   |
|Size                  |Medium                                                                                                                                                               |
|Type                  |undead                                                                                                                                                               |
|subtype1              |                                                                                                                                                                     |
|subtype2              |                                                                                                                                                                     |
|subtype3              |                                                                                                                                                                     |
|subtype4              |                                                                                                                                                                     |
|subtype5              |                                                                                                                                                                     |
|subtype6              |                                                                                                                                                                     |
|AC                    |25                                                                                                                                                                   |
|AC_Touch              |15                                                                                                                                                                   |
|AC_Flat.footed        |20                                                                                                                                                                   |
|HP                    |127                                                                                                                                                                  |
|HD                    |15d8+60                                                                                                                                                              |
|Fort                  |9                                                                                                                                                                    |
|Ref                   |9                                                                                                                                                                    |
|Will                  |11                                                                                                                                                                   |
|Melee                 |bastard sword +18/+13/+8 (1d10+6/17-20) or slam +17 (1d4+9 plus energy drain)                                                                                        |
|Ranged                |                                                                                                                                                                     |
|Space                 |5                                                                                                                                                                    |
|Reach                 |5                                                                                                                                                                    |
|Str                   |23                                                                                                                                                                   |
|Dex                   |18                                                                                                                                                                   |
|Con                   |-                                                                                                                                                                    |
|Int                   |13                                                                                                                                                                   |
|Wis                   |15                                                                                                                                                                   |
|Cha                   |18                                                                                                                                                                   |
|Feats                 |Cleave, Dodge, Great Cleave, Improved Critical (bastard sword), Mobility, Power Attack, Spring Attack, Weapon Focus (bastard sword)                                  |
|Skills                |Acrobatics +10 (+14 when jumping), Disguise +15, Intimidate +20, Knowledge (engineering) +12, Knowledge (religion) +12, Perception +20, Sense Motive +9, Stealth +17 |
|RacialMods            |                                                                                                                                                                     |
|Languages             |Common, Necril                                                                                                                                                       |
|SQ                    |unkillable                                                                                                                                                           |
|Environment           |any                                                                                                                                                                  |
|Organization          |solitary                                                                                                                                                             |
|Treasure              |standard (bastard sword, other gear)                                                                                                                                 |
|Group                 |                                                                                                                                                                     |
|Gear                  |                                                                                                                                                                     |
|OtherGear             |                                                                                                                                                                     |
|CharacterFlag         |0                                                                                                                                                                    |
|CompanionFlag         |0                                                                                                                                                                    |
|Speed                 |40 ft.                                                                                                                                                               |
|Base_Speed            |40                                                                                                                                                                   |
|Fly_Speed             |                                                                                                                                                                     |
|Maneuverability       |                                                                                                                                                                     |
|Climb_Speed           |                                                                                                                                                                     |
|Swim_Speed            |                                                                                                                                                                     |
|Burrow_Speed          |                                                                                                                                                                     |
|Speed_Special         |                                                                                                                                                                     |
|Speed_Land            |1                                                                                                                                                                    |
|Fly                   |0                                                                                                                                                                    |
|Climb                 |0                                                                                                                                                                    |
|Burrow                |0                                                                                                                                                                    |
|Swim                  |0                                                                                                                                                                    |
|VariantParent         |NULL                                                                                                                                                                 |
|ClassArchetypes       |                                                                                                                                                                     |
|CompanionFamiliarLink |NULL                                                                                                                                                                 |
|AlternateNameForm     |                                                                                                                                                                     |
|id                    |4444                                                                                                                                                                 |
|UniqueMonster         |0                                                                                                                                                                    |
|MR                    |0                                                                                                                                                                    |
|Mythic                |0                                                                                                                                                                    |
|MT                    |0                                                                                                                                                                    |
|Source                |AP 71                                                                                                                                                                |
|N                     |6                                                                                                                                                                    |
|hp                    |139  , 134  , 123  , 140  , 122  , 134                                                                                                                               |


###Room 6


|                      |2234                                                                      |
|:---------------------|:-------------------------------------------------------------------------|
|Name                  |Skvader                                                                   |
|CR                    |0.5                                                                       |
|XP                    |200                                                                       |
|Race                  |                                                                          |
|Class1                |                                                                          |
|Class1_Lvl            |NA                                                                        |
|Class2                |                                                                          |
|Class2_Lvl            |NA                                                                        |
|Alignment             |N                                                                         |
|Size                  |Tiny                                                                      |
|Type                  |magical beast                                                             |
|subtype1              |                                                                          |
|subtype2              |                                                                          |
|subtype3              |                                                                          |
|subtype4              |                                                                          |
|subtype5              |                                                                          |
|subtype6              |                                                                          |
|AC                    |14                                                                        |
|AC_Touch              |14                                                                        |
|AC_Flat.footed        |12                                                                        |
|HP                    |6                                                                         |
|HD                    |1d10+1                                                                    |
|Fort                  |3                                                                         |
|Ref                   |4                                                                         |
|Will                  |1                                                                         |
|Melee                 |bite +5 (1d3-1 plus attach)                                               |
|Ranged                |                                                                          |
|Space                 |2/1/2002                                                                  |
|Reach                 |0                                                                         |
|Str                   |8                                                                         |
|Dex                   |15                                                                        |
|Con                   |13                                                                        |
|Int                   |4                                                                         |
|Wis                   |13                                                                        |
|Cha                   |6                                                                         |
|Feats                 |Weapon Finesse                                                            |
|Skills                |Stealth +14                                                               |
|RacialMods            |                                                                          |
|Languages             |                                                                          |
|SQ                    |                                                                          |
|Environment           |temperate forest and hills                                                |
|Organization          |solitary, pair, family (3-12), or pack (1 wolpertinger and 3-12 skvaders) |
|Treasure              |none                                                                      |
|Group                 |                                                                          |
|Gear                  |                                                                          |
|OtherGear             |                                                                          |
|CharacterFlag         |0                                                                         |
|CompanionFlag         |0                                                                         |
|Speed                 |40 ft., fly 40 ft. (poor)                                                 |
|Base_Speed            |40                                                                        |
|Fly_Speed             |                                                                          |
|Maneuverability       |poor                                                                      |
|Climb_Speed           |                                                                          |
|Swim_Speed            |                                                                          |
|Burrow_Speed          |                                                                          |
|Speed_Special         |                                                                          |
|Speed_Land            |1                                                                         |
|Fly                   |1                                                                         |
|Climb                 |0                                                                         |
|Burrow                |0                                                                         |
|Swim                  |0                                                                         |
|VariantParent         |                                                                          |
|ClassArchetypes       |                                                                          |
|CompanionFamiliarLink |NULL                                                                      |
|AlternateNameForm     |                                                                          |
|id                    |3356                                                                      |
|UniqueMonster         |0                                                                         |
|MR                    |0                                                                         |
|Mythic                |0                                                                         |
|MT                    |0                                                                         |
|Source                |AP 61                                                                     |
|N                     |1                                                                         |
|hp                    |8                                                                         |


###Room 7


|                      |2622                                                                                                                                          |
|:---------------------|:---------------------------------------------------------------------------------------------------------------------------------------------|
|Name                  |Vulnudaemon                                                                                                                                   |
|CR                    |4                                                                                                                                             |
|XP                    |1,200                                                                                                                                         |
|Race                  |                                                                                                                                              |
|Class1                |                                                                                                                                              |
|Class1_Lvl            |NA                                                                                                                                            |
|Class2                |                                                                                                                                              |
|Class2_Lvl            |NA                                                                                                                                            |
|Alignment             |NE                                                                                                                                            |
|Size                  |Small                                                                                                                                         |
|Type                  |outsider                                                                                                                                      |
|subtype1              |daemon                                                                                                                                        |
|subtype2              |evil                                                                                                                                          |
|subtype3              |extraplanar                                                                                                                                   |
|subtype4              |                                                                                                                                              |
|subtype5              |                                                                                                                                              |
|subtype6              |                                                                                                                                              |
|AC                    |17                                                                                                                                            |
|AC_Touch              |14                                                                                                                                            |
|AC_Flat.footed        |14                                                                                                                                            |
|HP                    |39                                                                                                                                            |
|HD                    |6d10+6                                                                                                                                        |
|Fort                  |6                                                                                                                                             |
|Ref                   |5                                                                                                                                             |
|Will                  |6                                                                                                                                             |
|Melee                 |short sword +10/+5 (1d4+2/19-20 plus bleed), bite +5 (1d3+1)                                                                                  |
|Ranged                |                                                                                                                                              |
|Space                 |5                                                                                                                                             |
|Reach                 |5                                                                                                                                             |
|Str                   |14                                                                                                                                            |
|Dex                   |17                                                                                                                                            |
|Con                   |13                                                                                                                                            |
|Int                   |12                                                                                                                                            |
|Wis                   |13                                                                                                                                            |
|Cha                   |16                                                                                                                                            |
|Feats                 |Ability Focus (aura of doom), Combat Casting, Weapon Finesse                                                                                  |
|Skills                |Bluff +12, Diplomacy +10, Fly +11, Knowledge (arcana) +7, Knowledge (planes) +8, Perception +10, Sense Motive +10, Spellcraft +8, Stealth +16 |
|RacialMods            |                                                                                                                                              |
|Languages             |Abyssal, Draconic, Infernal; telepathy 100 ft.                                                                                                |
|SQ                    |                                                                                                                                              |
|Environment           |any (Abaddon)                                                                                                                                 |
|Organization          |solitary, pair, or murder (3-12)                                                                                                              |
|Treasure              |standard                                                                                                                                      |
|Group                 |Daemon                                                                                                                                        |
|Gear                  |                                                                                                                                              |
|OtherGear             |                                                                                                                                              |
|CharacterFlag         |0                                                                                                                                             |
|CompanionFlag         |0                                                                                                                                             |
|Speed                 |30 ft.                                                                                                                                        |
|Base_Speed            |30                                                                                                                                            |
|Fly_Speed             |                                                                                                                                              |
|Maneuverability       |                                                                                                                                              |
|Climb_Speed           |                                                                                                                                              |
|Swim_Speed            |                                                                                                                                              |
|Burrow_Speed          |                                                                                                                                              |
|Speed_Special         |                                                                                                                                              |
|Speed_Land            |1                                                                                                                                             |
|Fly                   |0                                                                                                                                             |
|Climb                 |0                                                                                                                                             |
|Burrow                |0                                                                                                                                             |
|Swim                  |0                                                                                                                                             |
|VariantParent         |                                                                                                                                              |
|ClassArchetypes       |                                                                                                                                              |
|CompanionFamiliarLink |NULL                                                                                                                                          |
|AlternateNameForm     |                                                                                                                                              |
|id                    |2010                                                                                                                                          |
|UniqueMonster         |0                                                                                                                                             |
|MR                    |0                                                                                                                                             |
|Mythic                |0                                                                                                                                             |
|MT                    |0                                                                                                                                             |
|Source                |PFRPG Bestiary 3                                                                                                                              |
|N                     |1                                                                                                                                             |
|hp                    |29                                                                                                                                            |


###Room 8


|                      |2574                                                                                                                                                                              |
|:---------------------|:---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------|
|Name                  |Very Old Brass Dragon                                                                                                                                                             |
|CR                    |15                                                                                                                                                                                |
|XP                    |51,200                                                                                                                                                                            |
|Race                  |                                                                                                                                                                                  |
|Class1                |                                                                                                                                                                                  |
|Class1_Lvl            |NA                                                                                                                                                                                |
|Class2                |                                                                                                                                                                                  |
|Class2_Lvl            |NA                                                                                                                                                                                |
|Alignment             |CG                                                                                                                                                                                |
|Size                  |Huge                                                                                                                                                                              |
|Type                  |dragon                                                                                                                                                                            |
|subtype1              |fire                                                                                                                                                                              |
|subtype2              |                                                                                                                                                                                  |
|subtype3              |                                                                                                                                                                                  |
|subtype4              |                                                                                                                                                                                  |
|subtype5              |                                                                                                                                                                                  |
|subtype6              |                                                                                                                                                                                  |
|AC                    |35                                                                                                                                                                                |
|AC_Touch              |8                                                                                                                                                                                 |
|AC_Flat.footed        |35                                                                                                                                                                                |
|HP                    |250                                                                                                                                                                               |
|HD                    |20d12+120                                                                                                                                                                         |
|Fort                  |18                                                                                                                                                                                |
|Ref                   |12                                                                                                                                                                                |
|Will                  |16                                                                                                                                                                                |
|Melee                 |bite +28 (2d8+15), 2 claws +28 (2d6+10), 2 wings +26 (1d8+5), tail slap +26 (2d6+15)                                                                                              |
|Ranged                |                                                                                                                                                                                  |
|Space                 |15                                                                                                                                                                                |
|Reach                 |15 (20 with bite)                                                                                                                                                                 |
|Str                   |31                                                                                                                                                                                |
|Dex                   |10                                                                                                                                                                                |
|Con                   |23                                                                                                                                                                                |
|Int                   |18                                                                                                                                                                                |
|Wis                   |19                                                                                                                                                                                |
|Cha                   |18                                                                                                                                                                                |
|Feats                 |Alertness, Flyby Attack, Hover, Greater Spell Focus (enchantment), Improved Initiative, Improved Vital Strike, Multiattack, Power Attack, Spell Focus (enchantment), Vital Strike |
|Skills                |Bluff +27, Diplomacy +27, Fly +15, Heal +27, Knowledge (local) +27, Linguistics +27, Perception +31, Sense Motive +31, Spellcraft +27, Survival +27                               |
|RacialMods            |                                                                                                                                                                                  |
|Languages             |Common, Draconic, plus any 22 more                                                                                                                                                |
|SQ                    |move sand                                                                                                                                                                         |
|Environment           |warm deserts                                                                                                                                                                      |
|Organization          |solitary                                                                                                                                                                          |
|Treasure              |triple                                                                                                                                                                            |
|Group                 |Metallic Dragon                                                                                                                                                                   |
|Gear                  |                                                                                                                                                                                  |
|OtherGear             |                                                                                                                                                                                  |
|CharacterFlag         |0                                                                                                                                                                                 |
|CompanionFlag         |0                                                                                                                                                                                 |
|Speed                 |60 ft., burrow 30 ft., fly 200 ft. (poor)                                                                                                                                         |
|Base_Speed            |60                                                                                                                                                                                |
|Fly_Speed             |                                                                                                                                                                                  |
|Maneuverability       |poor                                                                                                                                                                              |
|Climb_Speed           |                                                                                                                                                                                  |
|Swim_Speed            |                                                                                                                                                                                  |
|Burrow_Speed          |30                                                                                                                                                                                |
|Speed_Special         |                                                                                                                                                                                  |
|Speed_Land            |1                                                                                                                                                                                 |
|Fly                   |1                                                                                                                                                                                 |
|Climb                 |0                                                                                                                                                                                 |
|Burrow                |1                                                                                                                                                                                 |
|Swim                  |0                                                                                                                                                                                 |
|VariantParent         |                                                                                                                                                                                  |
|ClassArchetypes       |                                                                                                                                                                                  |
|CompanionFamiliarLink |NULL                                                                                                                                                                              |
|AlternateNameForm     |                                                                                                                                                                                  |
|id                    |1568                                                                                                                                                                              |
|UniqueMonster         |0                                                                                                                                                                                 |
|MR                    |0                                                                                                                                                                                 |
|Mythic                |0                                                                                                                                                                                 |
|MT                    |0                                                                                                                                                                                 |
|Source                |d20pfsrd                                                                                                                                                                          |
|N                     |1                                                                                                                                                                                 |
|hp                    |238                                                                                                                                                                               |


###Room 9


|                      |1539                                   |
|:---------------------|:--------------------------------------|
|Name                  |Lizard                                 |
|CR                    |0.17                                   |
|XP                    |65                                     |
|Race                  |                                       |
|Class1                |                                       |
|Class1_Lvl            |NA                                     |
|Class2                |                                       |
|Class2_Lvl            |NA                                     |
|Alignment             |N                                      |
|Size                  |Tiny                                   |
|Type                  |animal                                 |
|subtype1              |                                       |
|subtype2              |                                       |
|subtype3              |                                       |
|subtype4              |                                       |
|subtype5              |                                       |
|subtype6              |                                       |
|AC                    |14                                     |
|AC_Touch              |14                                     |
|AC_Flat.footed        |12                                     |
|HP                    |3                                      |
|HD                    |1d8-1                                  |
|Fort                  |1                                      |
|Ref                   |4                                      |
|Will                  |1                                      |
|Melee                 |bite +4 (1d4-4)                        |
|Ranged                |                                       |
|Space                 |2/1/2002                               |
|Reach                 |0                                      |
|Str                   |3                                      |
|Dex                   |15                                     |
|Con                   |8                                      |
|Int                   |1                                      |
|Wis                   |12                                     |
|Cha                   |2                                      |
|Feats                 |Weapon Finesse                         |
|Skills                |Acrobatics +10, Climb +10, Stealth +14 |
|RacialMods            |+8 Acrobatics                          |
|Languages             |                                       |
|SQ                    |                                       |
|Environment           |any temperate or warm                  |
|Organization          |solitary, pair, or nest (3-8)          |
|Treasure              |none                                   |
|Group                 |Familiar                               |
|Gear                  |                                       |
|OtherGear             |                                       |
|CharacterFlag         |0                                      |
|CompanionFlag         |0                                      |
|Speed                 |20 ft., climb 20 ft.                   |
|Base_Speed            |20                                     |
|Fly_Speed             |                                       |
|Maneuverability       |                                       |
|Climb_Speed           |20                                     |
|Swim_Speed            |                                       |
|Burrow_Speed          |                                       |
|Speed_Special         |                                       |
|Speed_Land            |1                                      |
|Fly                   |0                                      |
|Climb                 |1                                      |
|Burrow                |0                                      |
|Swim                  |0                                      |
|VariantParent         |                                       |
|ClassArchetypes       |                                       |
|CompanionFamiliarLink |NULL                                   |
|AlternateNameForm     |                                       |
|id                    |184                                    |
|UniqueMonster         |0                                      |
|MR                    |0                                      |
|Mythic                |0                                      |
|MT                    |0                                      |
|Source                |PFRPG Bestiary                         |
|N                     |1                                      |
|hp                    |3                                      |


###Room 10


|                      |51                                                                                                                                                                                                       |
|:---------------------|:--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------|
|Name                  |Adult Vortex Dragon                                                                                                                                                                                      |
|CR                    |14                                                                                                                                                                                                       |
|XP                    |38,400                                                                                                                                                                                                   |
|Race                  |                                                                                                                                                                                                         |
|Class1                |                                                                                                                                                                                                         |
|Class1_Lvl            |NA                                                                                                                                                                                                       |
|Class2                |                                                                                                                                                                                                         |
|Class2_Lvl            |NA                                                                                                                                                                                                       |
|Alignment             |LN                                                                                                                                                                                                       |
|Size                  |Huge                                                                                                                                                                                                     |
|Type                  |dragon                                                                                                                                                                                                   |
|subtype1              |fire                                                                                                                                                                                                     |
|subtype2              |                                                                                                                                                                                                         |
|subtype3              |                                                                                                                                                                                                         |
|subtype4              |                                                                                                                                                                                                         |
|subtype5              |                                                                                                                                                                                                         |
|subtype6              |                                                                                                                                                                                                         |
|AC                    |30                                                                                                                                                                                                       |
|AC_Touch              |9                                                                                                                                                                                                        |
|AC_Flat.footed        |29                                                                                                                                                                                                       |
|HP                    |195                                                                                                                                                                                                      |
|HD                    |17d12+85                                                                                                                                                                                                 |
|Fort                  |17                                                                                                                                                                                                       |
|Ref                   |13                                                                                                                                                                                                       |
|Will                  |14                                                                                                                                                                                                       |
|Melee                 |bite +23 (2d8+12/19-20), 2 claws +23 (2d6+8), 2 wings +21 (1d8+4), tail slap +21 (2d6+12)                                                                                                                |
|Ranged                |                                                                                                                                                                                                         |
|Space                 |15                                                                                                                                                                                                       |
|Reach                 |10 (15 with bite)                                                                                                                                                                                        |
|Str                   |27                                                                                                                                                                                                       |
|Dex                   |12                                                                                                                                                                                                       |
|Con                   |21                                                                                                                                                                                                       |
|Int                   |20                                                                                                                                                                                                       |
|Wis                   |19                                                                                                                                                                                                       |
|Cha                   |20                                                                                                                                                                                                       |
|Feats                 |Flyby Attack, Great Fortitude, Improved Critical (bite), Improved Initiative, Lightning Reflexes, Multiattack, Power Attack, Snatch, Wingover                                                            |
|Skills                |Bluff +25, Diplomacy +25, Fly +21, Intimidate +25, Knowledge (arcana) +25, Knowledge (geography) +25, Knowledge (planes) +25, Knowledge (religion) +25, Perception +24, Sense Motive +24, Spellcraft +25 |
|RacialMods            |                                                                                                                                                                                                         |
|Languages             |Abyssal, Auran, Celestial, Common, Draconic, Infernal                                                                                                                                                    |
|SQ                    |agile, galactic emissary, no breath, starflight                                                                                                                                                          |
|Environment           |vacuum                                                                                                                                                                                                   |
|Organization          |solitary                                                                                                                                                                                                 |
|Treasure              |triple                                                                                                                                                                                                   |
|Group                 |Outer Dragon                                                                                                                                                                                             |
|Gear                  |                                                                                                                                                                                                         |
|OtherGear             |                                                                                                                                                                                                         |
|CharacterFlag         |0                                                                                                                                                                                                        |
|CompanionFlag         |0                                                                                                                                                                                                        |
|Speed                 |60 ft., fly 200 ft. (good)                                                                                                                                                                               |
|Base_Speed            |60                                                                                                                                                                                                       |
|Fly_Speed             |                                                                                                                                                                                                         |
|Maneuverability       |good                                                                                                                                                                                                     |
|Climb_Speed           |                                                                                                                                                                                                         |
|Swim_Speed            |                                                                                                                                                                                                         |
|Burrow_Speed          |                                                                                                                                                                                                         |
|Speed_Special         |                                                                                                                                                                                                         |
|Speed_Land            |1                                                                                                                                                                                                        |
|Fly                   |1                                                                                                                                                                                                        |
|Climb                 |0                                                                                                                                                                                                        |
|Burrow                |0                                                                                                                                                                                                        |
|Swim                  |0                                                                                                                                                                                                        |
|VariantParent         |                                                                                                                                                                                                         |
|ClassArchetypes       |                                                                                                                                                                                                         |
|CompanionFamiliarLink |NULL                                                                                                                                                                                                     |
|AlternateNameForm     |                                                                                                                                                                                                         |
|id                    |5195                                                                                                                                                                                                     |
|UniqueMonster         |0                                                                                                                                                                                                        |
|MR                    |0                                                                                                                                                                                                        |
|Mythic                |0                                                                                                                                                                                                        |
|MT                    |0                                                                                                                                                                                                        |
|Source                |PFRPG Bestiary 4                                                                                                                                                                                         |
|N                     |1                                                                                                                                                                                                        |
|hp                    |171                                                                                                                                                                                                      |
